import Foundation
import Network
import SystemConfiguration
import Security

enum ProxyRule: Equatable {
    case domain(String)          // e.g. "www.example.com" or "*.example.com"
    case ipv4(String)            // e.g. "10.0.0.5"
    case ipv4CIDR(net: String, mask: String) // e.g. net "192.168.1.0", mask "255.255.255.0"

    static func parse(_ raw: String) -> ProxyRule? {
        let s = raw.trimmingCharacters(in: .whitespaces)
        guard !s.isEmpty else { return nil }

        if let slash = s.firstIndex(of: "/") {
            let net = String(s[..<slash])
            let bitsStr = String(s[s.index(after: slash)...])
            guard isIPv4(net), let bits = Int(bitsStr), (0...32).contains(bits) else { return nil }
            return .ipv4CIDR(net: net, mask: mask(forPrefix: bits))
        }
        if isIPv4(s) {
            return .ipv4(s)
        }
        return .domain(s)
    }

    private static func isIPv4(_ s: String) -> Bool {
        let parts = s.split(separator: ".")
        guard parts.count == 4 else { return false }
        return parts.allSatisfy { p in
            if let n = Int(p), (0...255).contains(n) { return true }
            return false
        }
    }

    private static func mask(forPrefix bits: Int) -> String {
        var value: UInt32 = bits == 0 ? 0 : UInt32.max << (32 - bits)
        let a = (value >> 24) & 0xFF
        let b = (value >> 16) & 0xFF
        let c = (value >> 8) & 0xFF
        let d = value & 0xFF
        return "\(a).\(b).\(c).\(d)"
    }
}

class PACGenerator {
    static func makePAC(proxyHost: String, proxyPort: Int, rules: [ProxyRule]) -> String {
        let clauses: [String] = rules.map { rule in
            switch rule {
            case .domain(let pattern):
                return "  if (shExpMatch(host, \(jsString(pattern)))) return SOCKS;"
            case .ipv4(let ip):
                return "  if (host == \(jsString(ip))) return SOCKS;"
            case .ipv4CIDR(let net, let mask):
                return "  if (isInNet(host, \(jsString(net)), \(jsString(mask)))) return SOCKS;"
            }
        }
        return """
        // Generated by SwiftPipes — selective SOCKS routing.
        function FindProxyForURL(url, host) {
          var SOCKS = "SOCKS \(proxyHost):\(proxyPort); SOCKS5 \(proxyHost):\(proxyPort)";
          host = host.toLowerCase();
        \(clauses.joined(separator: "\n"))
          return "DIRECT";
        }
        """
    }

    private static func jsString(_ s: String) -> String {
        var escaped = ""
        for ch in s {
            switch ch {
            case "\\": escaped.append("\\\\")
            case "\"": escaped.append("\\\"")
            case "\n": escaped.append("\\n")
            case "\r": escaped.append("\\r")
            default: escaped.append(ch)
            }
        }
        return "\"\(escaped)\""
    }
}

class PACServer {
    private let queue = DispatchQueue(label: "com.swiftpipes.pacserver")
    private var listener: NWListener?
    private var connections: [ObjectIdentifier: NWConnection] = [:]
    private var pac: String = ""

    func start(pac: String) -> Int? {
        stop()
        self.pac = pac

        let params = NWParameters.tcp
        params.requiredInterfaceType = .loopback
        params.allowLocalEndpointReuse = true

        let listener: NWListener
        do {
            listener = try NWListener(using: params)
        } catch {
            print("PACServer: failed to create listener: \(error)")
            return nil
        }

        listener.newConnectionHandler = { [weak self] connection in
            self?.handle(connection)
        }

        let started = DispatchSemaphore(value: 0)
        var boundPort: Int?

        listener.stateUpdateHandler = { state in
            switch state {
            case .ready:
                if let p = listener.port?.rawValue {
                    boundPort = Int(p)
                }
                started.signal()
            case .failed(let err):
                print("PACServer: listener failed: \(err)")
                started.signal()
            case .cancelled:
                break
            default:
                break
            }
        }

        listener.start(queue: queue)
        _ = started.wait(timeout: .now() + 2)
        self.listener = listener
        return boundPort
    }

    func stop() {
        queue.sync {
            listener?.cancel()
            listener = nil
            for (_, c) in connections { c.cancel() }
            connections.removeAll()
        }
    }

    func updatePAC(_ newPAC: String) {
        queue.sync { self.pac = newPAC }
    }

    private func handle(_ connection: NWConnection) {
        let key = ObjectIdentifier(connection)
        connections[key] = connection

        connection.stateUpdateHandler = { [weak self] state in
            switch state {
            case .cancelled, .failed:
                self?.queue.async { self?.connections.removeValue(forKey: key) }
            default:
                break
            }
        }

        connection.start(queue: queue)
        receiveRequest(connection)
    }

    private func receiveRequest(_ connection: NWConnection) {
        connection.receive(minimumIncompleteLength: 1, maximumLength: 4096) { [weak self] data, _, _, error in
            guard let self = self else { return }
            if let error = error {
                print("PACServer: receive error: \(error)")
                connection.cancel()
                return
            }
            // We don't actually need the request body — just respond with the PAC.
            _ = data
            let body = self.pac
            let headers = [
                "HTTP/1.1 200 OK",
                "Content-Type: application/x-ns-proxy-autoconfig",
                "Content-Length: \(body.utf8.count)",
                "Cache-Control: no-store",
                "Connection: close",
                "",
                ""
            ].joined(separator: "\r\n")
            let response = headers + body
            connection.send(content: response.data(using: .utf8), completion: .contentProcessed { _ in
                connection.cancel()
            })
        }
    }
}

class NetworkProxyManager {
    private let keychainAccount = "admin-password"
    private var pacServer: PACServer?

    func enableSOCKSProxy(host: String, port: Int) {
        let services = getNetworkServices()
        print("Enabling SOCKS proxy for services: \(services)")

        var commands: [String] = []
        for service in services {
            let escaped = shellEscape(service)
            // Turn off any lingering PAC auto-proxy before enabling classic SOCKS,
            // so a prior selective-mode session can't leave PAC active alongside.
            commands.append("/usr/sbin/networksetup -setautoproxystate '\(escaped)' off")
            commands.append("/usr/sbin/networksetup -setsocksfirewallproxy '\(escaped)' '\(host)' '\(port)'")
            commands.append("/usr/sbin/networksetup -setsocksfirewallproxystate '\(escaped)' on")
        }

        if !commands.isEmpty {
            runCommandsBatch(commands)
        }

        // Also stop our own PAC server if it was left running from a previous
        // selective-mode session.
        pacServer?.stop()
        pacServer = nil
    }

    func disableSOCKSProxy() {
        let services = getNetworkServices()
        print("Disabling SOCKS proxy for services: \(services)")

        var commands: [String] = []
        for service in services {
            let escaped = shellEscape(service)
            commands.append("/usr/sbin/networksetup -setsocksfirewallproxystate '\(escaped)' off")
        }

        if !commands.isEmpty {
            runCommandsBatch(commands)
        }
    }

    func enableSelectiveSOCKS(host: String, port: Int, rules: [ProxyRule]) -> Bool {
        let pac = PACGenerator.makePAC(proxyHost: host, proxyPort: port, rules: rules)

        let server = pacServer ?? PACServer()
        guard let pacPort = server.start(pac: pac) else {
            print("Selective SOCKS: failed to start local PAC server")
            return false
        }
        pacServer = server

        let pacURL = "http://127.0.0.1:\(pacPort)/proxy.pac"
        let services = getNetworkServices()
        print("Enabling selective SOCKS via PAC \(pacURL) for services: \(services)")

        var commands: [String] = []
        for service in services {
            let escaped = shellEscape(service)
            commands.append("/usr/sbin/networksetup -setautoproxyurl '\(escaped)' '\(pacURL)'")
            commands.append("/usr/sbin/networksetup -setautoproxystate '\(escaped)' on")
            // Make sure the legacy "everything-via-SOCKS" switch is off, in case it was set.
            commands.append("/usr/sbin/networksetup -setsocksfirewallproxystate '\(escaped)' off")
        }

        if !commands.isEmpty {
            runCommandsBatch(commands)
        }
        return true
    }

    func disableSelectiveSOCKS() {
        let services = getNetworkServices()
        print("Disabling selective SOCKS for services: \(services)")

        var commands: [String] = []
        for service in services {
            let escaped = shellEscape(service)
            commands.append("/usr/sbin/networksetup -setautoproxystate '\(escaped)' off")
        }

        if !commands.isEmpty {
            runCommandsBatch(commands)
        }

        pacServer?.stop()
        pacServer = nil
    }

    func disableAllProxyConfig() {
        let services = getNetworkServices()
        var commands: [String] = []
        for service in services {
            let escaped = shellEscape(service)
            commands.append("/usr/sbin/networksetup -setsocksfirewallproxystate '\(escaped)' off")
            commands.append("/usr/sbin/networksetup -setautoproxystate '\(escaped)' off")
        }
        if !commands.isEmpty {
            runCommandsBatch(commands)
        }
        pacServer?.stop()
        pacServer = nil
    }

    /// Read-only probe (no sudo) to detect stale system proxy state from a
    /// previous crash/force-quit. `networksetup -get*` commands don't require
    /// elevated privileges, so calling this on every launch is silent.
    func isAnyProxyActive() -> Bool {
        for service in getNetworkServices() {
            if isSOCKSOn(service: service) || isAutoProxyOn(service: service) {
                return true
            }
        }
        return false
    }

    private func isSOCKSOn(service: String) -> Bool {
        return runReadOnly(args: ["-getsocksfirewallproxy", service])
            .contains("Enabled: Yes")
    }

    private func isAutoProxyOn(service: String) -> Bool {
        return runReadOnly(args: ["-getautoproxyurl", service])
            .contains("Enabled: Yes")
    }

    private func runReadOnly(args: [String]) -> String {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/sbin/networksetup")
        process.arguments = args
        let pipe = Pipe()
        process.standardOutput = pipe
        process.standardError = Pipe() // silence
        do {
            try process.run()
            process.waitUntilExit()
            let data = pipe.fileHandleForReading.readDataToEndOfFile()
            return String(data: data, encoding: .utf8) ?? ""
        } catch {
            return ""
        }
    }

    private func shellEscape(_ s: String) -> String {
        s.replacingOccurrences(of: "'", with: "'\\''")
    }

    private func getNetworkServices() -> [String] {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/sbin/networksetup")
        process.arguments = ["-listallnetworkservices"]

        let pipe = Pipe()
        process.standardOutput = pipe

        do {
            try process.run()
            process.waitUntilExit()

            let data = pipe.fileHandleForReading.readDataToEndOfFile()
            if let output = String(data: data, encoding: .utf8) {
                let lines = output.components(separatedBy: .newlines)
                return lines
                    .dropFirst()
                    .filter { !$0.isEmpty && !$0.hasPrefix("*") }
            }
        } catch {
            print("Failed to get network services: \(error)")
        }

        return []
    }

    private func runCommandsBatch(_ commands: [String]) {
        // Get password from keychain ONCE
        var password = KeychainHelper.shared.get(forKey: keychainAccount)

        // If no password, prompt for it (max 3 attempts)
        var attempts = 0
        while password == nil && attempts < 3 {
            password = promptForPassword()
            if let pwd = password {
                if KeychainHelper.shared.save(pwd, forKey: keychainAccount) {
                    break
                }
            }
            attempts += 1
        }

        guard let pwd = password else {
            print("No password provided after \(attempts) attempts")
            return
        }

        // Escape the password for shell
        let escapedPassword = pwd.replacingOccurrences(of: "'", with: "'\\''")

        // Combine all commands with &&
        let combinedCommand = commands.joined(separator: " && ")

        // Escape the combined command for nested shell
        let escapedCommand = combinedCommand.replacingOccurrences(of: "'", with: "'\\''")

        // Use printf instead of echo to avoid issues with special characters
        let fullCommand = "printf '%s\\n' '\(escapedPassword)' | sudo -S sh -c '\(escapedCommand)'"

        // Use sudo with password via stdin - SINGLE execution
        let task = Process()
        task.executableURL = URL(fileURLWithPath: "/bin/sh")

        let outputPipe = Pipe()
        let errorPipe = Pipe()
        task.standardOutput = outputPipe
        task.standardError = errorPipe

        task.arguments = ["-c", fullCommand]

        do {
            try task.run()
            task.waitUntilExit()

            if task.terminationStatus == 0 {
                print("Successfully configured network proxy")
            } else {
                let errorData = errorPipe.fileHandleForReading.readDataToEndOfFile()
                if let error = String(data: errorData, encoding: .utf8), !error.isEmpty {
                    // Filter out just the "Password:" prompt from stderr
                    let filteredError = error.components(separatedBy: .newlines)
                        .filter { !$0.trimmingCharacters(in: .whitespaces).isEmpty && $0 != "Password:" }
                        .joined(separator: "\n")

                    if !filteredError.isEmpty {
                        print("Network configuration failed")
                    }

                    if error.contains("Sorry, try again") || error.contains("incorrect password") {
                        _ = KeychainHelper.shared.delete(forKey: keychainAccount)
                        // Try again with iteration instead of recursion
                        var retryPassword: String?
                        var retryAttempts = 0
                        while retryAttempts < 2 {
                            retryPassword = promptForPassword()
                            if let pwd = retryPassword {
                                if KeychainHelper.shared.save(pwd, forKey: keychainAccount) {
                                    runCommandsBatch(commands)
                                    return
                                }
                            }
                            retryAttempts += 1
                        }
                    }
                }
            }
        } catch {
            print("Failed to execute network configuration")
        }
    }

    private func promptForPassword() -> String? {
        let script = """
        display dialog "SwiftPipes needs your administrator password to configure network settings. Your password will be saved securely in Keychain." default answer "" with title "Administrator Password Required" with icon caution with hidden answer
        """

        let task = Process()
        task.launchPath = "/usr/bin/osascript"
        task.arguments = ["-e", script]

        let pipe = Pipe()
        task.standardOutput = pipe

        do {
            try task.run()
            task.waitUntilExit()

            if task.terminationStatus == 0 {
                let data = pipe.fileHandleForReading.readDataToEndOfFile()
                if var result = String(data: data, encoding: .utf8) {
                    if let range = result.range(of: "text returned:") {
                        result = String(result[range.upperBound...])
                            .trimmingCharacters(in: .whitespacesAndNewlines)
                        return result
                    }
                }
            }
        } catch {
            print("Failed to prompt for password: \(error)")
        }

        return nil
    }
}
